---
# This playbook deploys two simple applications to JBoss server. 

- hosts: all
  become: yes
  become_method: sudo

  roles:
# Optionally, (re)deploy JBoss here	  
#    - jboss-standalone
    - java-app
